[package]
name = "GitChat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
eframe = "0.23.0"
egui = "0.23.0"
ratatui = "0.24.0"
serde_json = "1.0.108"
